"""empty message

Revision ID: 26865b578cee
Revises: 7f92da584cc9
Create Date: 2024-08-01 13:11:38.910377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26865b578cee'
down_revision = '7f92da584cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
