"""empty message

Revision ID: 2ba669d44978
Revises: 26865b578cee
Create Date: 2024-08-01 14:25:21.915480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba669d44978'
down_revision = '26865b578cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_user_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_user_notes_gym_id_gyms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gym_user_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=500), nullable=True))

    op.drop_table('gym_user_notes')
    # ### end Alembic commands ###
