"""empty message

Revision ID: 69d598929019
Revises: 9f90f48bbc90
Create Date: 2024-07-08 13:06:18.533690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d598929019'
down_revision = '9f90f48bbc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('instructor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('rating')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
