"""empty message

Revision ID: 70a8934e3156
Revises: 69ddfb0e8976
Create Date: 2024-07-31 19:11:13.069382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a8934e3156'
down_revision = '69ddfb0e8976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
