"""empty message

Revision ID: 7f92da584cc9
Revises: d4df16ff2dfa
Create Date: 2024-08-01 11:41:36.774963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f92da584cc9'
down_revision = 'd4df16ff2dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
