"""empty message

Revision ID: d4df16ff2dfa
Revises: 70a8934e3156
Create Date: 2024-08-01 09:54:44.352702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4df16ff2dfa'
down_revision = '70a8934e3156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('gym_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
